name: theminisupermarket
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+45

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  carousel_pro: ^0.0.13
  firebase_auth: ^0.11.1+7
  cloud_firestore: ^0.12.5+2
  google_sign_in: ^4.0.2
  shared_preferences: ^0.5.3+1
  fluttertoast: ^3.1.0
  firebase_core: ^0.4.0+6
  firebase_database: ^3.0.3
  english_words: ^3.1.3
  pin_entry_text_field: ^0.1.3
  intl: ^0.15.8
  rxdart: ^0.19.0
  flutter_offline: ^0.2.4+1
  flip_card: ^0.3.0
  firebase_messaging:
  flutter_local_notifications:
  path_provider:
  firebase_storage:
  sticky_headers:
  flutter_datetime_picker:
  font_awesome:
  carousel_slider:
  font_awesome_flutter:
  geocoder:
  google_maps_flutter:
  flutter_google_places: 
  flutter_map:
  location:
  geolocator:
  firebase_remote_config:
  package_info:
  url_launcher:  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  image_path: "images/grocery-cart-launcher-justG.png"
  ios: true


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/aashirvaad-atta.jpg
    - images/aashirvaad-chilli-powder.png
    - images/amul-butter.jpg
    - images/bourbon-orginal.png
    - images/products/aashirvaad-salt.png
    - images/products/amul-cheese-slices.jpg
    - images/products/amul-masti.jpg
    - images/products/comfort-blue.jpg
    - images/products/everest-chicken-masala.jpg
    - images/products/jersey-gold.jpg
    - images/products/santoor-almond.jpg
    - images/products/tata-salt-crystal.jpg
    - images/amul-gold.jpg
    - images/amul-ghee-box.png
    - images/amul-taaza.png
    - images/comfort-pink.jpg
    - images/everest-garam-masala.jpg
    - images/shopping-trolley.jpg
    - images/kiranawala-logo.jpg
    - images/kiranawala.jpg
    - images/categories/baby-care.jpg
    - images/categories/dry-fruits-nuts.jpg
    - images/categories/home-care.jpg
    - images/categories/kirana.png
    - images/categories/oral-care.jpg
    - images/categories/personal-care.jpg
    - images/categories/pooja.jpg
    - images/categories/pulses-cereals.png
    - images/categories/dairy-products.png
    - images/categories/vegetables.png
    - images/categories/chocolates.jpg
    - images/categories/dry-fruits-nuts-spices-herbs.png
    - images/categories/dry-fruits-nuts.jpg
    - images/categories/feminine-hygiene.jpg
    - images/categories/malt-drinks.jpg
    - images/categories/jams-sauces-ketchups.jpg
    - images/categories/powdered-spices-herbs.jpg
    - images/categories/whole-spices-herbs-2.png
    - images/categories/tea-coffee-mixes.jpg
    - images/categories/biscuits.jpg
    - images/categories/snacks.jpg
    - images/categories/fabric-care.jpg
    - images/categories/fruits.png
    - images/categories/cool-drinks.png
    - images/categories/cooking-oils.jpg
    - images/categories/pulses-cereals-2.jpg
    - images/categories/atta-rava.jpg
    - images/categories/breakfast-bread-eggs.jpg
    - images/categories/electrical-accessories.jpg
    - images/categories/ice-creams.jpg
    - images/categories/frozen-veg.jpg
    - images/categories/fresh-non-veg.jpg
    - images/categories/pickles-chutneys.jpg
    - images/categories/cigarettes.jpg
    - images/categories/otc-medicines.jpg
    - images/categories/beauty-products.jpg
    - images/categories/deodorants.jpg
    - images/categories/hair-care.jpg
    - images/categories/oral-care.jpg
    - images/categories/bath-products.jpg
    - images/categories/baby-diapers.jpg
    - images/categories/baby-products.jpg
    - images/categories/namkeen.png
    - images/categories/frozen-snacks.jpg
    - images/categories/chocolates-2.jpg
    - images/categories/biscuits.jpg
    - images/categories/chips.jpg
    - images/categories/cakes.png
    - images/categories/sweets.jpg
    - images/categories/soft-drinks.jpg
    - images/categories/milkshake.png
    - images/categories/fruit-juice.jpg
    - images/categories/water.jpg
    - images/categories/air-freshener.png
    - images/categories/antiseptic-liquids.jpg
    - images/categories/pest-control.jpg
    - images/categories/surface-cleaner.jpg
    - images/categories/toilet-cleaner.jpg
    - images/categories/fabric-care.jpg
    - images/categories/personal-care.jpg
    - images/categories/pooja.jpg
    - images/categories/steel.jpg
    - images/categories/plastic.jpg
    - images/categories/disposables.jpg
    - images/categories/party.jpg
    - images/categories/stationery.jpeg
    - images/categories/leafy-veg.jpg
    - images/categories/non-leafy.jpg
    - images/categories/baby-care.jpg
    - images/categories/ice-creams.jpg
    - images/categories/flours.png
    - images/categories/eggs.jpg
    - images/categories/curd.jfif
    - images/categories/cheese.jpg
    - images/categories/cake.png
    - images/categories/fresh-cream.jpg
    - images/categories/popcorn.jpg
    - images/categories/paneer.jpg
    - images/categories/milk.jpg
    - images/categories/butter.jpg
    - images/categories/bread.png
    - images/categories/breakfast-cereals.jpg
    - images/categories/spread-syrup.jpg
    - images/categories/jams-sauces-ketchups.jpg
    - images/categories/vermicelli.jpg
    - images/categories/baking.jpg
    - images/categories/noodles.jpg
    - images/categories/shaving-cream-foam-2.jpg
    - images/categories/rice-3.png
    - images/categories/rice-4.jpg
    - images/categories/roll-on.png
    - images/categories/shaving-razor.jpg
    - images/categories/pooja-oil.jpg
    - images/categories/pooja-wicks.jpg
    - images/categories/lipbalm.jpg
    - images/categories/garbage-bags.jpg
    - images/categories/hair-color.jpg
    - images/categories/hair-oil.jpg
    - images/categories/hair-gel.jpeg
    - images/categories/hair-removal-cream.jpg
    - images/categories/body-wash.jfif
    - images/categories/after-shave.png
    - images/categories/after-wash.jpg
    - images/categories/agarbathi.jpg
    - images/categories/air-freshener.jpg
    - images/categories/aluminium-foil.jpg
    - images/categories/baby-health.jpg
    - images/categories/cooking-paste.jpg
    - images/categories/deodorant.png
    - images/categories/detergent-bars.jpeg
    - images/categories/detergent-liquids.jpg
    - images/categories/detergent-powders.jpg
    - images/categories/dhoop.jpg
    - images/categories/dish-wash-bar.jpg
    - images/categories/dish-wash-liquid.jpg
    - images/categories/dish-wash-scrubber.jpg
    - images/categories/fabric-stain-remover.png
    - images/categories/floor-cleaner.jpg
    - images/categories/haldi-kumkum.jpg
    - images/categories/lipbalm.jpg
    - images/categories/makeup.jpg
    - images/categories/talcum-powder.jpeg
    - images/categories/tongue-cleaner.jpg
    - images/categories/toothpaste.jpg
    - images/categories/mouthwash.jpg
    - images/categories/multi-surface-cleaner.jpg
    - images/categories/body-wash.jfif
    - images/categories/bath-products.jpg
    - images/categories/bath-powder.jpg
    - images/categories/face-wash.jpg
    - images/categories/face-cream.jpg
    - images/categories/toothbrushes.webp
    - images/categories/toothpaste.jpg
    - images/categories/tongue-cleaner.jpg
    - images/categories/paper-napkins.jpg
    - images/categories/batteries.jpg
    - images/categories/paper-napkins.jpg
    - images/categories/antiseptic-liquids.jpg
    - images/categories/perfume.jpg
    - images/categories/body-lotion.png
    - images/categories/sunscreen.jpg
    - images/categories/lipbalm.jpg
    - images/categories/dhoop.jpg
    - images/categories/camphor.jpg
    - images/categories/haldi-kumkum.jpg
    - images/categories/shampoo.jpg
    - images/categories/baby-diapers.jpg
    - images/categories/baby-health.jpg
    - images/categories/baby-lotion.jpg
    - images/categories/baby-oil.jpg
    - images/categories/baby-powder.jpg
    - images/categories/baby-shampoo.jpg
    - images/categories/baby-soaps.jpg
    - images/categories/aluminium-foil.jpg
    - images/categories/cling-film.jpg
    - images/categories/disposables.jpg
    - images/categories/paper-napkins.jpg
    - images/categories/garbage-bags.jpg
    - images/categories/rice-3.png
    - images/categories/sauce.jpg
    - images/categories/ketchup.jpg
    - images/categories/vinegar.jpg
    - images/categories/honey-banner.jpg
    - images/categories/pantyliner.jfif
    - images/categories/sanitary-pads.jpg
    - images/categories/intimate-hygiene.jpg
    - images/categories/whole-spices-herbs-2.png
    - images/categories/powdered-spices-herbs.jpg
    - images/categories/mixed-spices.jpg
    - images/categories/rodent-control.jpg
    - images/categories/tea.jpg
    - images/categories/coffee.jpg
    - images/categories/sunflower-oil.jpg
    - images/categories/palm-oil.jpg
    - images/categories/groundnut-oil.jpg
    - images/categories/gingelly-oil.jpg
    - images/categories/olive-oil.jpg
    - images/categories/ricebran-oil.jpg
    - images/categories/vegetable-oil.png
    - images/categories/desi-cow.png
    - images/categories/desi-buffalo.jpg
    - images/categories/vanaspati.jpg
    - images/categories/instant-breakfast.jpg
    - images/categories/instant-meals.jpeg
    - images/categories/instant-noodles.jpg
    - images/categories/instant-pasta.jpg
    - images/categories/instant-sweet-mix.jpg
    - images/categories/chutney-powder.jpg
    - images/app-logo.png
    - images/banners/fruits.jpg
    - images/banners/vegetables.jpg
    - images/banners/pulses-cereals.jpg
    - images/banners/beverages.jpg
    - images/banners/dairy-products.jpg
    - images/banners/dry-fruits-nuts.jpg
    - images/banners/personal-care.jpg
    - images/banners/home-care.jpg
    - images/banners/edible-oils-ghee.png
    - images/banners/spice-mixes.png
    - images/banners/water-cans.png
    - images/categories/chicken-live.jpeg
    - images/categories/goat-live-2.png
    - images/categories/sea-food.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf        
    